    name: Threagile Threat Model Analysis

    on:
      push:
        paths:
          - 'threagile.yaml' # Trigger this workflow when threagile.yaml changes
      workflow_dispatch: # Allows manual triggering of the workflow

    jobs:
      threagile_job:
        runs-on: ubuntu-latest
        name: Threat Model Analysis

        steps:
          - name: Checkout Workspace
            uses: actions/checkout@v4 # Use the latest version of checkout action

          - name: Run Threagile
            id: threagile
            uses: threagile/run-threagile-action@v1 # Use the Threagile GitHub Action
            with:
              model-file: 'threagile.yaml' # Specify the path to your Threagile model file

          - name: Archive Results
            uses: actions/upload-artifact@v4 # Use the latest version of upload-artifact action
            with:
              name: threagile-report
              path: threagile/output # Path where Threagile outputs its results
