title: "Sample Web App Threat Model"
author: "Your Name"
date: "2025-09-11"

technical_assets:
  webapp:
    id: webapp
    description: Public Web Application
    type: web-server
    usage: business
    confidentiality: confidential
    integrity: critical
    availability: critical
    internet: true

  database:
    id: database
    description: Backend Database
    type: database
    usage: business
    confidentiality: strictly-confidential
    integrity: critical
    availability: important

communication_links:
  webapp_to_db:
    source: webapp
    target: database
    protocol: sql
    authentication: credentials
    confidentiality: confidential
    integrity: critical
    availability: important
