name: Threagile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  threat-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Threagile
      run: |
        wget https://github.com/Threagile/threagile/releases/latest/download/threagile-linux-amd64
        chmod +x threagile-linux-amd64
        sudo mv threagile-linux-amd64 /usr/local/bin/threagile

    - name: Validate Model
      run: threagile validate --model threatspec/models/generic.yaml

    - name: Run Threagile Report
      run: threagile report --model threatspec/models/generic.yaml --output reports

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: threagile-reports
        path: threatspec/reports/
