name: Threagile Threat Modeling

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main
  pull_request:

jobs:
  threagile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull official Threagile image
        run: docker pull ghcr.io/threagile/threagile:latest

      - name: Run Threagile
        run: |
          mkdir -p output
          docker run --rm \
            -v ${{ github.workspace }}:/data \
            ghcr.io/threagile/threagile:latest \
            -model /data/model.yaml \
            -output /data/output

      - name: Upload Threagile reports
        uses: actions/upload-artifact@v4
        with:
          name: threagile-reports
          path: output/
