name: Threagile CI using Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  threat-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Ensure Reports Folder Exists
      run: mkdir -p reports

    - name: Run Threagile via Docker
      run: |
        docker pull threagile/threagile:latest
        docker run --rm -v "${{ github.workspace }}":/work -w /work threagile/threagile \
          --model ./threagile.yaml \
          --output ./reports \
          --verbose

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: threagile-reports
        path: .
