name: Threagile Threat Model

on:
  workflow_dispatch:

jobs:
  threagile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Threagile
        run: |
          git clone https://github.com/Threagile/threagile tools/threagile
          cd tools/threagile
          go build -o ../../threagile-local .

      - name: Run Threagile
        run: ./threagile-local --model threatspec/models/threagile.yaml --output threatspec/reports

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: threagile-reports
          path: threatspec/reports
